import { collection, doc, Firestore } from "firebase/firestore";

// Function to generate a new unique ID using Firestore
export const newId = (db: Firestore) => {
  // Creating a new reference to the "ontology" collection in the Firestore database
  const newRef = doc(collection(db, "ontology"));
  
  // Returning the unique ID generated by Firestore for the new reference
  return newRef.id;
};
