options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: "E2_HIGHCPU_32"

steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology || exit 0",
      ]

  # Restore Next.js build cache from GCS
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil cp gs://${PROJECT_ID}_cloudbuild/cache/next-cache.tar.gz next-cache.tar.gz && \
        tar -xzf next-cache.tar.gz || echo "No cache found, creating empty directory." && mkdir -p .next_cache

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [
        "-c",
        'docker build --target builder -t us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology:builder
        --cache-from us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology
        --build-arg=PROD_ONTOLOGY_CRED_TYPE="$${PROD_ONTOLOGY_CRED_TYPE}"
        --build-arg=PROD_ONTOLOGY_CRED_PROJECT_ID="$${PROD_ONTOLOGY_CRED_PROJECT_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID="$${PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_PRIVATE_KEY="$${PROD_ONTOLOGY_CRED_PRIVATE_KEY}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_EMAIL="$${PROD_ONTOLOGY_CRED_CLIENT_EMAIL}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_ID="$${PROD_ONTOLOGY_CRED_CLIENT_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_AUTH_URI="$${PROD_ONTOLOGY_CRED_AUTH_URI}"
        --build-arg=PROD_ONTOLOGY_CRED_TOKEN_URI="$${PROD_ONTOLOGY_CRED_TOKEN_URI}"
        --build-arg=PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL="$${PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL="$${PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL}"
        --build-arg=PROD_ONTOLOGY_STORAGE_BUCKET="$${PROD_ONTOLOGY_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_API_KEY="$${NEXT_PUBLIC_API_KEY}"
        --build-arg=NEXT_PUBLIC_AUTH_DOMAIN="$${NEXT_PUBLIC_AUTH_DOMAIN}"
        --build-arg=NEXT_PUBLIC_PROJECT_ID="$${NEXT_PUBLIC_PROJECT_ID}"
        --build-arg=NEXT_PUBLIC_STORAGE_BUCKET="$${NEXT_PUBLIC_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_MESSAGING_SENDER_ID}"
        --build-arg=NEXT_PUBLIC_APP_ID="$${NEXT_PUBLIC_APP_ID}"
        --build-arg=NEXT_PUBLIC_DATABASE_URL="$${NEXT_PUBLIC_DATABASE_URL}"
        --build-arg=NEXT_PUBLIC_DEV_API_KEY="$${NEXT_PUBLIC_DEV_API_KEY}"
        --build-arg=NEXT_PUBLIC_DEV_AUTH_DOMAIN="$${NEXT_PUBLIC_DEV_AUTH_DOMAIN}"
        --build-arg=NEXT_PUBLIC_DEV_PROJECT_ID="$${NEXT_PUBLIC_DEV_PROJECT_ID}"
        --build-arg=NEXT_PUBLIC_DEV_STORAGE_BUCKET="$${NEXT_PUBLIC_DEV_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID}"
        --build-arg=NEXT_PUBLIC_DEV_APP_ID="$${NEXT_PUBLIC_DEV_APP_ID}"
        .',
      ]

    env:
      - "DOCKER_BUILDKIT=1"
      - "NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}"
      - "NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}"
      - "NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}"
      - "NEXT_PUBLIC_DATABASE_URL=${_NEXT_PUBLIC_DATABASE_URL}"
      - "NEXT_PUBLIC_DEV_API_KEY=${_NEXT_PUBLIC_DEV_API_KEY}"
      - "NEXT_PUBLIC_DEV_AUTH_DOMAIN=${_NEXT_PUBLIC_DEV_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_DEV_PROJECT_ID=${_NEXT_PUBLIC_DEV_PROJECT_ID}"
      - "NEXT_PUBLIC_DEV_STORAGE_BUCKET=${_NEXT_PUBLIC_DEV_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_DEV_APP_ID=${_NEXT_PUBLIC_DEV_APP_ID}"
    secretEnv:
      [
        "PROD_ONTOLOGY_CRED_TYPE",
        "PROD_ONTOLOGY_CRED_PROJECT_ID",
        "PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID",
        "PROD_ONTOLOGY_CRED_PRIVATE_KEY",
        "PROD_ONTOLOGY_CRED_CLIENT_EMAIL",
        "PROD_ONTOLOGY_CRED_CLIENT_ID",
        "PROD_ONTOLOGY_CRED_AUTH_URI",
        "PROD_ONTOLOGY_CRED_TOKEN_URI",
        "PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL",
        "PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL",
        "PROD_ONTOLOGY_STORAGE_BUCKET",
      ]

  # Extract Next.js build cache from the BUILDER image and save to GCS
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        id=$(docker create us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology:builder) && \
        docker cp $id:/app/.next/cache .next_cache && \
        docker rm -v $id && \
        tar -czf next-cache.tar.gz .next_cache
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "next-cache.tar.gz",
        "gs://${PROJECT_ID}_cloudbuild/cache/next-cache.tar.gz",
      ]

  # Build the FINAL container image (fast due to cached layers)
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: [
        "-c",
        'docker build -t us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology
        --cache-from us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology
        --build-arg=PROD_ONTOLOGY_CRED_TYPE="$${PROD_ONTOLOGY_CRED_TYPE}"
        --build-arg=PROD_ONTOLOGY_CRED_PROJECT_ID="$${PROD_ONTOLOGY_CRED_PROJECT_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID="$${PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_PRIVATE_KEY="$${PROD_ONTOLOGY_CRED_PRIVATE_KEY}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_EMAIL="$${PROD_ONTOLOGY_CRED_CLIENT_EMAIL}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_ID="$${PROD_ONTOLOGY_CRED_CLIENT_ID}"
        --build-arg=PROD_ONTOLOGY_CRED_AUTH_URI="$${PROD_ONTOLOGY_CRED_AUTH_URI}"
        --build-arg=PROD_ONTOLOGY_CRED_TOKEN_URI="$${PROD_ONTOLOGY_CRED_TOKEN_URI}"
        --build-arg=PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL="$${PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL}"
        --build-arg=PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL="$${PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL}"
        --build-arg=PROD_ONTOLOGY_STORAGE_BUCKET="$${PROD_ONTOLOGY_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_API_KEY="$${NEXT_PUBLIC_API_KEY}"
        --build-arg=NEXT_PUBLIC_AUTH_DOMAIN="$${NEXT_PUBLIC_AUTH_DOMAIN}"
        --build-arg=NEXT_PUBLIC_PROJECT_ID="$${NEXT_PUBLIC_PROJECT_ID}"
        --build-arg=NEXT_PUBLIC_STORAGE_BUCKET="$${NEXT_PUBLIC_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_MESSAGING_SENDER_ID}"
        --build-arg=NEXT_PUBLIC_APP_ID="$${NEXT_PUBLIC_APP_ID}"
        --build-arg=NEXT_PUBLIC_DATABASE_URL="$${NEXT_PUBLIC_DATABASE_URL}"
        --build-arg=NEXT_PUBLIC_DEV_API_KEY="$${NEXT_PUBLIC_DEV_API_KEY}"
        --build-arg=NEXT_PUBLIC_DEV_AUTH_DOMAIN="$${NEXT_PUBLIC_DEV_AUTH_DOMAIN}"
        --build-arg=NEXT_PUBLIC_DEV_PROJECT_ID="$${NEXT_PUBLIC_DEV_PROJECT_ID}"
        --build-arg=NEXT_PUBLIC_DEV_STORAGE_BUCKET="$${NEXT_PUBLIC_DEV_STORAGE_BUCKET}"
        --build-arg=NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID="$${NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID}"
        --build-arg=NEXT_PUBLIC_DEV_APP_ID="$${NEXT_PUBLIC_DEV_APP_ID}"
        .',
      ]
    env:
      - "DOCKER_BUILDKIT=1"
      - "NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}"
      - "NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}"
      - "NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}"
      - "NEXT_PUBLIC_DATABASE_URL=${_NEXT_PUBLIC_DATABASE_URL}"
      - "NEXT_PUBLIC_DEV_API_KEY=${_NEXT_PUBLIC_DEV_API_KEY}"
      - "NEXT_PUBLIC_DEV_AUTH_DOMAIN=${_NEXT_PUBLIC_DEV_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_DEV_PROJECT_ID=${_NEXT_PUBLIC_DEV_PROJECT_ID}"
      - "NEXT_PUBLIC_DEV_STORAGE_BUCKET=${_NEXT_PUBLIC_DEV_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_DEV_APP_ID=${_NEXT_PUBLIC_DEV_APP_ID}"
    secretEnv:
      [
        "PROD_ONTOLOGY_CRED_TYPE",
        "PROD_ONTOLOGY_CRED_PROJECT_ID",
        "PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID",
        "PROD_ONTOLOGY_CRED_PRIVATE_KEY",
        "PROD_ONTOLOGY_CRED_CLIENT_EMAIL",
        "PROD_ONTOLOGY_CRED_CLIENT_ID",
        "PROD_ONTOLOGY_CRED_AUTH_URI",
        "PROD_ONTOLOGY_CRED_TOKEN_URI",
        "PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL",
        "PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL",
        "PROD_ONTOLOGY_STORAGE_BUCKET",
      ]
  # Push the NextJS container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology",
      ]
  # Deploy the NextJS container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "ontology",
        "--image",
        "us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology",
        "--region",
        "us-central1",
        "--project",
        "ontology-41607",
        "--allow-unauthenticated",
      ]

images:
  - us-central1-docker.pkg.dev/ontology-41607/ontology-repo/ontology
availableSecrets:
  secretManager:
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_TYPE/versions/1
      env: "PROD_ONTOLOGY_CRED_TYPE"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_PROJECT_ID/versions/1
      env: "PROD_ONTOLOGY_CRED_PROJECT_ID"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID/versions/1
      env: "PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_PRIVATE_KEY/versions/1
      env: "PROD_ONTOLOGY_CRED_PRIVATE_KEY"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_CLIENT_EMAIL/versions/1
      env: "PROD_ONTOLOGY_CRED_CLIENT_EMAIL"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_CLIENT_ID/versions/1
      env: "PROD_ONTOLOGY_CRED_CLIENT_ID"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_AUTH_URI/versions/1
      env: "PROD_ONTOLOGY_CRED_AUTH_URI"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_TOKEN_URI/versions/1
      env: "PROD_ONTOLOGY_CRED_TOKEN_URI"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL/versions/1
      env: "PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL/versions/1
      env: "PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL"
    - versionName: projects/163479774214/secrets/PROD_ONTOLOGY_STORAGE_BUCKET/versions/1
      env: "PROD_ONTOLOGY_STORAGE_BUCKET"

timeout: 2000s
