# Use Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json* ./

RUN apk add --no-cache python3

RUN npm ci --legacy-peer-deps

# Copy project files
COPY src ./src
COPY public ./public
COPY next.config.js ./
COPY tsconfig.json ./

ARG PROD_ONTOLOGY_CRED_TYPE
ARG PROD_ONTOLOGY_CRED_PROJECT_ID
ARG PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID
ARG PROD_ONTOLOGY_CRED_PRIVATE_KEY
ARG PROD_ONTOLOGY_CRED_CLIENT_EMAIL
ARG PROD_ONTOLOGY_CRED_CLIENT_ID
ARG PROD_ONTOLOGY_CRED_AUTH_URI
ARG PROD_ONTOLOGY_CRED_TOKEN_URI
ARG PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL
ARG PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL
ARG PROD_ONTOLOGY_STORAGE_BUCKET
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_DATABASE_URL

ARG NEXT_PUBLIC_DEV_API_KEY
ARG NEXT_PUBLIC_DEV_AUTH_DOMAIN
ARG NEXT_PUBLIC_DEV_PROJECT_ID
ARG NEXT_PUBLIC_DEV_STORAGE_BUCKET
ARG NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_DEV_APP_ID

ENV PROD_ONTOLOGY_CRED_TYPE=${PROD_ONTOLOGY_CRED_TYPE}
ENV PROD_ONTOLOGY_CRED_PROJECT_ID=${PROD_ONTOLOGY_CRED_PROJECT_ID}
ENV PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID=${PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID}
ENV PROD_ONTOLOGY_CRED_PRIVATE_KEY=${PROD_ONTOLOGY_CRED_PRIVATE_KEY}
ENV PROD_ONTOLOGY_CRED_CLIENT_EMAIL=${PROD_ONTOLOGY_CRED_CLIENT_EMAIL}
ENV PROD_ONTOLOGY_CRED_CLIENT_ID=${PROD_ONTOLOGY_CRED_CLIENT_ID}
ENV PROD_ONTOLOGY_CRED_AUTH_URI=${PROD_ONTOLOGY_CRED_AUTH_URI}
ENV PROD_ONTOLOGY_CRED_TOKEN_URI=${PROD_ONTOLOGY_CRED_TOKEN_URI}
ENV PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL=${PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL}
ENV PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL=${PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL}
ENV PROD_ONTOLOGY_STORAGE_BUCKET=${PROD_ONTOLOGY_STORAGE_BUCKET}
ENV NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
ENV NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
ENV NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
ENV NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
ENV NEXT_PUBLIC_DATABASE_URL=${NEXT_PUBLIC_DATABASE_URL}

ENV NEXT_PUBLIC_DEV_API_KEY=${NEXT_PUBLIC_DEV_API_KEY}
ENV NEXT_PUBLIC_DEV_AUTH_DOMAIN=${NEXT_PUBLIC_DEV_AUTH_DOMAIN}
ENV NEXT_PUBLIC_DEV_PROJECT_ID=${NEXT_PUBLIC_DEV_PROJECT_ID}
ENV NEXT_PUBLIC_DEV_STORAGE_BUCKET=${NEXT_PUBLIC_DEV_STORAGE_BUCKET}
ENV NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID=${NEXT_PUBLIC_DEV_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_DEV_APP_ID=${NEXT_PUBLIC_DEV_APP_ID}

ENV NODE_ENV=production

# Restore cache from previous build
COPY .next_cache ./.next/cache

RUN npm run build

# Step 2. Production image, copy all the files and run next
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN apk add --no-cache libc6-compat

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs


USER nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js .
COPY --from=builder /app/package.json .

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Environment variables must be redefined at run time

ARG PROD_ONTOLOGY_CRED_TYPE
ARG PROD_ONTOLOGY_CRED_PROJECT_ID
ARG PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID
ARG PROD_ONTOLOGY_CRED_PRIVATE_KEY
ARG PROD_ONTOLOGY_CRED_CLIENT_EMAIL
ARG PROD_ONTOLOGY_CRED_CLIENT_ID
ARG PROD_ONTOLOGY_CRED_AUTH_URI
ARG PROD_ONTOLOGY_CRED_TOKEN_URI
ARG PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL
ARG PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL
ARG PROD_ONTOLOGY_STORAGE_BUCKET
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_DATABASE_URL

ENV PROD_ONTOLOGY_CRED_TYPE=${PROD_ONTOLOGY_CRED_TYPE}
ENV PROD_ONTOLOGY_CRED_PROJECT_ID=${PROD_ONTOLOGY_CRED_PROJECT_ID}
ENV PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID=${PROD_ONTOLOGY_CRED_PRIVATE_KEY_ID}
ENV PROD_ONTOLOGY_CRED_PRIVATE_KEY=${PROD_ONTOLOGY_CRED_PRIVATE_KEY}
ENV PROD_ONTOLOGY_CRED_CLIENT_EMAIL=${PROD_ONTOLOGY_CRED_CLIENT_EMAIL}
ENV PROD_ONTOLOGY_CRED_CLIENT_ID=${PROD_ONTOLOGY_CRED_CLIENT_ID}
ENV PROD_ONTOLOGY_CRED_AUTH_URI=${PROD_ONTOLOGY_CRED_AUTH_URI}
ENV PROD_ONTOLOGY_CRED_TOKEN_URI=${PROD_ONTOLOGY_CRED_TOKEN_URI}
ENV PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL=${PROD_ONTOLOGY_CRED_AUTH_PROVIDER_X509_CERT_URL}
ENV PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL=${PROD_ONTOLOGY_CRED_CLIENT_X509_CERT_URL}
ENV PROD_ONTOLOGY_STORAGE_BUCKET=${PROD_ONTOLOGY_STORAGE_BUCKET}
ENV NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
ENV NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
ENV NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
ENV NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
ENV NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
ENV NEXT_PUBLIC_DATABASE_URL=${NEXT_PUBLIC_DATABASE_URL}

EXPOSE 3000
CMD ["node", "server.js"]